workflows:
  ios-release:
    name: Build iOS Release
    environment:
      groups:
        - pickupcoletador
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.app.wra6351acda948515228f31e632
    scripts:
      - name: Build .ipa
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
