workflows:
  ios-release:
    name: iOS Release Build
    environment:
      flutter: stable
      xcode: latest
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.app.wra6351acda948515228f31e632

      # Aqui você adiciona seu variable group
      groups:
        - pickupcoletador

    scripts:
      - name: Get dependencies
        script: flutter pub get

      - name: Build iOS release
        script: flutter build ipa --release --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/ipa/*.dSYM.zip

    integrations:
      app_store_connect: pickupcoletador  # nome da integração (se for o mesmo do variable group, ok)

    publishing:
      app_store_connect:
        auth: integration
