integrations:
  app_store_connect: pickupcoletador

workflows:
  ios-release:
    name: iOS Release Build
    environment:
      flutter: stable
      xcode: latest
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.app.wra6351acda948515228f31e632
    scripts:
      - name: Get dependencies
        script: flutter pub get

      - name: Build iOS release
        script: flutter build ipa --release --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/ipa/*.dSYM.zip

    publishing:
      app_store_connect:
        auth: integration
